#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.scripts"
export PATH="${PATH}:$HOME/.config/bspwm"

## Coloring
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
# Merged in the default .xinitrc
# xrdb ~/.Xresources

xset +fp ~/.fonts # Inform the X server of new directories
xset fp rehash    # Forces a new rescan

COLOR=~/.colors/vluvy
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR
paintee
# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi

## Bspwm configurations
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config focus_follows_pointer true
bspc config border_width 3
bspc config window_gap 8
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false

bspc config top_padding 8
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

## Window rules
# remove all rules first
bspc rule -r *:*
# 1 > terminal
# bspc rule -a URxvt desktop='^1' follow=on focus=on
# 2 > code
bspc desktop ^2 -l monocle
bspc rule -a code-oss desktop='^2' follow=on focus=on
# 3 > web
bspc desktop ^3 -l monocle
bspc rule -a Firefox desktop='^3' follow=on focus=on
bspc rule -a Chromium desktop='^3' follow=on focus=on


# 6 > settings
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
# System-config-printer.py Pavucontrol Exo-helper-1)
# for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done
# bspc rule -a GParted desktop='^6' follow=on focus=on

# special rules
# bspc rule -a Audacious state=floating follow=on focus=on
# bspc rule -a Firefox:Places state=floating follow=on focus=on
# bspc rule -a Viewnior state=floating follow=on focus=on
# bspc rule -a Conky state=floating manage=off
# bspc rule -a stalonetray state=floating manage=off

## Autostart
xsetroot -cursor_name left_ptr
xbacklight -set 10

killall -9 sxhkd dunst
sxhkd &
xsettingsd &
compton -b

dunst \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$GREEN" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$FOREGROUND" -cfr "$RED" &
sleep 0.5

feh --bg-fill ~/.wallpaper/bicycle.jpg

~/.config/polybar/launch.sh &
notify-send "Bspwm Loaded" "With $SHORTCOLOR color scheme"
