#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 46 -theme "archi"  \
    -width 10 -hide-scrollbar \
    -lines 4 -font "Lucida Grande 16" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) notify-send 'Locked!' ;;
                *Logout) bspc quit && exit ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
