#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -yoffset -75 \
    -xoffset -69 -width 15 -hide-scrollbar -line-padding 4 -padding 20 \
    -lines 4 -font "Lucida Grande 16" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) notify-send 'Locked!' ;;
                *Logout) bspc quit && exit ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac